# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update dependencies
on:
  pull_request:
  schedule:
    - cron: "43 21 * * *"
  workflow_dispatch:
jobs:
  dependabot:
    name: Merge automatic pull requests
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 12
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - name: Collect update metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout this repo
        if: steps.metadata.outputs.package-ecosystem == 'go_modules'
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: "0"
          persist-credentials: true
          ref: ${{ github.head_ref }}
      - name: Configure git credentials
        if: steps.metadata.outputs.package-ecosystem == 'go_modules'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Install a flaked Nix
        if: steps.metadata.outputs.package-ecosystem == 'go_modules'
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Update hashed dependencies
        if: steps.metadata.outputs.package-ecosystem == 'go_modules'
        run: |
          nix develop -c go mod tidy
          sed -i 's|vendorHash = \"[^"]*\";|vendorHash = \"\";|' flake.nix
          nix run .# --log-format internal-json 2&> vendors.json || true
          VENDORHASH="$(grep -o 'sha256-[^ ]*=' vendors.json | tail -n 1)"
          sed -i 's|vendorHash = \"\";|vendorHash = \"'"$VENDORHASH"'\";|' flake.nix
          git diff
          git add flake.nix go.mod go.sum
          git commit -m "chore(deps): update go dependencies vendor hash to the packages"
          git push -u origin "$GH_REF"
        env:
          GH_REF: ${{ github.head_ref }}
      - name: Start the tests
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/tests.yaml/dispatches" \
             -f "ref=$GH_REF"
        env:
          GH_REF: ${{ github.head_ref }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Take a snapshot
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/release.yaml/dispatches" \
             -f "ref=$GH_REF"
        env:
          GH_REF: ${{ github.head_ref }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@3603e826ee561ea102b58accb5ea55a1a7482343 # v1.4.1
        with:
          check-name: "Inspect the code health"
          ref: ${{ github.head_ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for a testing benchmark
        uses: lewagon/wait-on-check-action@3603e826ee561ea102b58accb5ea55a1a7482343 # v1.4.1
        with:
          check-name: "Monitor energy usage"
          ref: ${{ github.head_ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
      - name: Wait for packaging to pass
        uses: lewagon/wait-on-check-action@3603e826ee561ea102b58accb5ea55a1a7482343 # v1.4.1
        with:
          check-name: "Save a snapshot"
          ref: ${{ github.head_ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
      - name: Merge requests from the kind dependabot
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Perform more tests
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/tests.yaml/dispatches" \
             -f "ref=main"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Bundle with packages
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/release.yaml/dispatches" \
             -f "ref=main"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
  flake:
    name: Freeze the latest lockfile
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: true
          ref: main
      - name: Configure git credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Checkout an update
        run: |
          git checkout -b update
      - name: Update to the latest
        run: |
          nix flake update
      - name: Check for changes
        id: diff
        run: |
          if ! git diff --quiet; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Save the flake locks
        if: steps.diff.outputs.changed == 'true'
        run: |
          git commit --all --message "chore(deps): automatic version bump to the most recent packages"
          git push -u origin update
      - name: Start the tests
        if: steps.diff.outputs.changed == 'true'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/tests.yaml/dispatches" \
             -f "ref=update"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Wait for tests to succeed
        if: steps.diff.outputs.changed == 'true'
        uses: lewagon/wait-on-check-action@3603e826ee561ea102b58accb5ea55a1a7482343 # v1.4.1
        with:
          check-name: "Inspect the code health"
          ref: update
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for a testing benchmark
        if: steps.diff.outputs.changed == 'true'
        uses: lewagon/wait-on-check-action@3603e826ee561ea102b58accb5ea55a1a7482343 # v1.4.1
        with:
          check-regexp: "Monitor energy usage"
          ref: update
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
      - name: Save changed version
        if: steps.diff.outputs.changed == 'true'
        run: |
          git checkout main
          git merge update
          git push -u origin main
          git push origin --delete update
      - name: Confirm the tests
        if: steps.diff.outputs.changed == 'true'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/tests.yaml/dispatches" \
             -f "ref=main"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Share with updates
        if: steps.diff.outputs.changed == 'true'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GH_REPO/actions/workflows/release.yaml/dispatches" \
             -f "ref=main"
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
