# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Makes valid measurements
on:
  push:
  workflow_dispatch:
jobs:
  checkup:
    name: Inspect the code health
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Install dependencies
        run: nix develop -c go get
      - name: Check formatting
        run: nix develop -c make check
      - name: Build binary
        run: nix develop -c make build
      - name: Run tests
        run: nix develop -c make coverage
      - name: Upload coverage results
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          disable_search: true
          files: coverage/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          disable_search: true
          files: coverage/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
  measurement:
    name: Monitor energy usage
    needs: checkup
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Reflect existing Nix
        id: nixos
        continue-on-error: true
        run: uname -a | grep NixOS
      - name: Install a flaked Nix
        if: steps.nixos.outcome != 'success'
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Clean the environment
        run: nix develop -c make clean
      - name: Sleep for a short while
        run: |
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# sleep 4'
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
      - name: Sleep for a bit longer
        run: |
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# sleep 12'
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
      - name: End with an exit code
        run: |
          set +e
          nix develop .#tom -c sops exec-env vault.testing.json 'nix run .# dream'
          STATUS=$?
          echo $STATUS
          [ "$STATUS" -eq 127 ] || exit 1
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_TESTING_KEY }}
